### PR TITLE
Add support for sqlite in the absence of NOW() and UNIX_TIMESTAMP().

### PR DESCRIPTION
**Pull request by GableTheSnail**
Hello,

Your plugin is quite essential to roundcube - and thank you for creating it! Unfortunately, I use sqlite for the database and the `NOW()` and `UNIX_TIMESTAMP()` functions are not available in sqlite. I have created a patch that works around this problem for sqlite:
- `UNIX_TIMESTAMP($field)` would equate to `strftime('%s', $field)` in sqlite such that I added a case for sqlite to use the strftime function instead.
- `NOW()` would equate to `strftime('%s', 'now')` in sqlite such that I have added a case for sqlite to compute `strftime('%s', 'now')` and for all others `UNIX_TIMESTAMP(NOW())` as it was before.

If you like this patch, please apply it or change it accordingly. I have tested on my setup and it works a treat.

Regards,
Eva

### CODE REVIEW

**Comment by dsoares** [comment]
Hi,

Thank you for this PR! However, i can not merge it because it would fail on mysql/mariadb.
With your code, `NOW()` would be translated to `UNIX_TIMESTAMP(NOW())` and the `INSERT`/`UPDATE` clauses would not work (they insert zeros).

I would like to accept your PR, but i suggest the following:
1. use `unixnow()` for all `NOW()` calls and keep the old `unixtimestamp()` for the others.
2. change `unixnow()` method to simply use `NOW()` for non sqlite db_providers.
3. change the `unixtimestamp() method`; in `case 'sqlite'`, if `$field` is `~ now()`, call `unixnow()`, otherwise keep the `strftime('%s', $field)`.

or other solution you find best :)
I'll wait for your feedback.

**Comment by dsoares** [comment]
Oh! one more important thing: i'm not the creator of the plugin, credits should go for dennylin93 (see the README). 
However, in 2013/2014 this project seemed unmaintained, with PRs from 2013 not answered or took almost a year to be answered (dennylin93/rcguard#7, dennylin93/rcguard#11, dennylin93/rcguard#13), and i needed the plugin to work ASAP (for larry skin, use the new recaptcha APIv2, ...), so i forked it.

**Comment by GableTheSnail** [comment]
That is of course a much better solution! Thanks for checking. :) Even if you are not the original author, you still know the code-base of the plugin much better than me! I just had to write something fast so it works with my sqlite setup. Thanks for finding a solution!

**Comment by dsoares** [comment]
Since you did not change your PR, I merged it anyway and then added the changes according to what i've said in https://github.com/dsoares/rcguard/pull/6#issuecomment-190191665.

**Comment by GableTheSnail** [comment]
Thank you for patching it. I'm sorry I did not respond sooner.

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#6

**Pull request merged**
