### PR TITLE
sqlite fix, tr local

### PR DESCRIPTION
**Pull request by cagdasbas**
sqlite now fix fixed, tr_TR localization file added

### CODE REVIEW

**Comment by dsoares** [comment]
Hi,
Why did you close the PR?

**Comment by cagdasbas** [comment]
Hi,
I've realized that I didn't push the actual fix for sqlite:) I'm going to push the fix then open a request again.

**Comment by cagdasbas** [comment]
I cleaned up the unixnow and fix the sqlite issue.

**Comment by cagdasbas** [comment]
It is kind of embarrassing now, I understand if you won't merge it.

**Comment by dsoares** [comment]
It's not embarrassing at all :) 
I just have to analyse and test before i merge. I can't do it right now, but i'll look to it later.
Thank you!

**Comment by dsoares** [comment]
Hi,

I reviewed your PR, but i can't merge it because it would fail on mysql/mariadb. Maybe for sqlite the simplification would work, but in mysql/mariadb i must have `NOW()` and `UNIX_TIMESTAMP(NOW())` (which are different).
However, i would like to merge the change you did in `function show_recaptcha`, which i totally agree, and your translation file. Would you kindly do a PR with that ?

**Comment by cagdasbas** [comment]
Hi,

Can you check the latest commit? As I understand, you are always keep the time as seconds in db. Why do you need a formatted string? If this commit does not work, I'll leave the unixnow alone and revert back to minimal sqlite fix.

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#7

**Pull request closed without merging**
