### PR TITLE
Correction RU translate

### PR DESCRIPTION
**Pull request by Ramzzes**
The translation was provided "test string"
In reCAPCHA2 very rarely need to see the test string

### CODE REVIEW

**Comment by dsoares** [comment]
Sorry, can you explain a little more your PR ? I did not understand why you want to change that text to something about "protection against robots".

**Comment by Ramzzes** [comment]
In Russian recapcha2 looks like this
It says "I am not a robot"



Old translate - "You specified an incorrect value for the test string"

An inexperienced user may be unclear, what is a test string.
No test string is not there.

**Comment by dsoares** [comment]
I agree with you. My doubt was that Google Translate did not translate it to something like "incorrect value for the test string" but... well, it's Google Translate! ;)
However, i think we don't need to say something like "protection against robots" or that we are logged or not. What do you think about changing your PR to translating the strings like this?

```
$messages['recaptchafailed'] = 'CAPTCHA verification failed!';
$messages['recaptchaempty'] = 'CAPTCHA verification empty!';
```

I would be thankful to you.

**Comment by Ramzzes** [comment]
OK, so well
I corrected the translation

**Comment by dsoares** [comment]
Thank you!!

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#11

**Pull request merged**
