### PR TITLE
sqlite fix, tr local, captcha column fix

### PR DESCRIPTION
**Pull request by cagdasbas**
Hi,

It seems that, if you force remove a commit, you cannot reopen a PR with a new commit.

Can you check the latest commit? As I understand, you are always keep the time as seconds in db. Why do you need a formatted string? If this commit does not work, I'll leave the unixnow alone and revert back to minimal fix.

### CODE REVIEW

**Comment by dsoares** [comment]
Hi,

Sorry for the late answer.
The `UNIX_TIMESTAMP()` is needed for calculations in seconds - so i need to convert the datetime to seconds. See `delete_rcguard()` and `flush_rcguard()`. 

If i use a simple `NOW()` call, it would return a formatted datetime string (like `2016-05-10 12:00:39`) and i would have to call other datetime functions to add  the `$rcmail->config->get('expire_time')`. I prefer to _do the math_ in seconds. 

So, i cannot accept your PR because it would break the code for MariaDB/MySQL users.

**Comment by dsoares** [comment]
One more thing: the database field types are DATETIME, not TIMESTAMP.

**Comment by cagdasbas** [comment]
Hi, I believe we can agree on this now. I rebase to the minimal changes. The reason of my confusion is field type I guess.

**Comment by dsoares** [comment]
Thank you!

**Comment by dsoares** [comment]
This issue was moved to dsoares/rcguard#8

**Pull request merged**
